library(pdftools)	    # pdf interface
library(stringr)        # for regexp
library(tesseract)      # for OCR for SentrySuite report date extraction
library(lubridate)      # for date formatting

# TODO: adapt to PDFs exported from new SentrySuite device. Uses signature "BODY".
#           CAVE regex should not match BODYPDF, which is the signature for JLab.

lufu_rename_path <- function(path){
    new_path <- NA
    txt <- pdf_text(path) 	# path to file to be imported
    report_type <- str_extract(txt, regex("\n((SPIRO_FVC)|(BODYPDF))"))
    
    if(grepl("SPIRO_FVC", report_type)){
        # report generated by SentrySuite.
        # Date cannot be extracted by pdf_text().
        # Use OCR instead.
        txt <- pdf_ocr_text(path)
    }
    
    if(!is.na(report_type)){
        # if either SentrySuite (SPIRO_FVC) or JLab (BODYPDF)
        # report signature are recognized: continue
        
        # extract date, format DD.MM.YY (SPIRO_FVC) or DD.MM.YYYY (BODYPDF)
        date <- str_extract(txt, regex("(Testdatum|Datum)\\s+\\d{2}\\.\\d{2}\\.\\d{2,4}"))
        # cut off everything but the actual date string
        date <- str_extract(date, regex("\\d{2}\\.\\d{2}\\.\\d{2,4}"))
        
        # extract time stamp
        time <- str_extract(txt, regex("(Testzeit|Zeit)\\s+\\d{2}\\:\\d{2}"))
        # cut off everything but the actual time string
        time <- str_extract(time, regex("\\d{2}\\:\\d{2}"))
        
        # format date time string
        ld <- dmy_hm(paste(date, time))
        ld <- format(ld, "%Y%m%d_%H%M")
        
        # get path with trunc of current file name, without ascending numbering and .pdf
        # do so by cutting of as many chars at end of string as '_<NUMBER>.pdf' has
        
        dir <- dirname(path)
        file <- basename(path)
        file_trunc <- str_sub(
            file,
            end = (nchar(file) - nchar(str_extract(file, regex("(?<=.{1,200})_\\d+\\.pdf"))))
        )
        export_folder_name <- paste0(
            "umbenannt_",
            format(lubridate::now(), "%Y%m%d%H%M")  # introduce folder with
            # unique name to
            # export to
        )
        export_dir <- paste0(
            dir, "/",
            export_folder_name
        )
        if(!file.exists(export_dir)){
            dir.create(export_dir)
        }
        new_file_trunc <- paste0(
            file_trunc,
            "_",
            ld
        )
        new_path_trunc <- paste0(
            export_dir,
            "/",
            new_file_trunc
        )
        if(file.exists(paste0(new_path_trunc, ".pdf"))){
            # count number of files with same name, i.e. reports of
            # measurements from same date, hour and minute, that are
            # already in the folder
            n <- grep(new_file_trunc, list.files(export_dir))
            new_path_trunc <- paste0(
                new_path_trunc,
                "_",
                n
            )
        }
        new_path <- paste0(
            new_path_trunc,
            ".pdf"
        )
        print(paste("new_path", new_path))
    }
    return(new_path)
}

paths <- choose.files(
    filters = Filters[c("pdf"),],
    default = "S:/C17/WKP/MUK/PCD/Untersuchungsbefunde (MBW_LuFu etc.)/PCD/*.*",
    multi = TRUE
)

new_paths <- sapply(paths, FUN=lufu_rename_path)
# note: has to use for loop, can't use sapply and
# file.copy(paths, new_paths, overwrite=FALSE) over
# vector, because then copying is multithreaded,
# bypassing checking if file already exists. Hence,
# reports from same date, hour and minute get overwritten.
for (path in paths) {
    file.copy(path, lufu_rename_path(path), overwrite=FALSE)
}